set_property SRC_FILE_INFO {cfile:C:/Users/sonal/OneDrive/Documents/ECE540_Winter/RVfpgaR1_0-main/src/liteDRAM.xdc rfile:../../../../../../../OneDrive/Documents/ECE540_Winter/RVfpgaR1_0-main/src/liteDRAM.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/sonal/OneDrive/Documents/ECE540_Winter/RVfpgaR1_0-main/src/rvfpga.xdc rfile:../../../../../../../OneDrive/Documents/ECE540_Winter/RVfpgaR1_0-main/src/rvfpga.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/sonal/Documents/GitHub/ECE540_Project2/project_2/project_2.srcs/constrs_1/new/optimized_project2.xdc rfile:../../../project_2.srcs/constrs_1/new/optimized_project2.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {ddram_dqs_n[1]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ddram_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V9 [get_ports {ddram_dqs_n[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {ddram_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {ddram_a[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {ddram_a[1]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {ddram_a[2]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {ddram_a[3]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddram_a[4]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {ddram_a[5]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {ddram_a[6]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {ddram_a[7]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {ddram_a[8]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {ddram_a[9]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {ddram_a[10]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddram_a[11]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {ddram_a[12]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {ddram_ba[0]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {ddram_ba[1]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {ddram_ba[2]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports ddram_ras_n]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports ddram_cas_n]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports ddram_we_n]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {ddram_dm[0]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {ddram_dm[1]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {ddram_dq[0]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports {ddram_dq[1]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {ddram_dq[2]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {ddram_dq[3]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports {ddram_dq[4]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {ddram_dq[5]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {ddram_dq[6]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {ddram_dq[7]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {ddram_dq[8]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {ddram_dq[9]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {ddram_dq[10]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {ddram_dq[11]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {ddram_dq[12]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports {ddram_dq[13]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {ddram_dq[14]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports {ddram_dq[15]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports ddram_clk_p]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports ddram_clk_n]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports ddram_cke]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports ddram_odt]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports ddram_cs_n]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports rstn]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports i_uart_rx]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports o_uart_tx]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports o_flash_mosi]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports i_flash_miso]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS33} [get_ports o_flash_cs_n]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {i_sw[0]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {i_sw[1]}]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {i_sw[2]}]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {i_sw[3]}]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {i_sw[4]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {i_sw[5]}]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {i_sw[6]}]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {i_sw[7]}]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {i_sw[8]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {i_sw[9]}]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {i_sw[10]}]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {i_sw[11]}]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {i_sw[12]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {i_sw[13]}]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {i_sw[14]}]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {i_sw[15]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {o_led[0]}]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {o_led[1]}]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {o_led[2]}]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {o_led[3]}]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {o_led[4]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {o_led[5]}]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {o_led[6]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {o_led[7]}]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {o_led[8]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {o_led[9]}]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {o_led[10]}]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {o_led[11]}]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {o_led[12]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {o_led[13]}]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {o_led[14]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {o_led[15]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports CA]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports CB]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports CC]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports CD]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports CE]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports CF]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports CG]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports DP]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports BTNU]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports BTNC]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports BTND]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports BTNL]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports BTNR]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33} [get_ports i_accel_miso]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports o_accel_mosi]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports accel_sclk]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports o_accel_cs_n]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {red_vga[0]}]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {red_vga[1]}]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {red_vga[2]}]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {red_vga[3]}]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {green_vga[0]}]
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {green_vga[1]}]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {green_vga[2]}]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {green_vga[3]}]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {blue_vga[0]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {blue_vga[1]}]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {blue_vga[2]}]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {blue_vga[3]}]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports hsync_pin]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports vsync_pin]
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/gpio_rojobot/sync_reg[24]}]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[0]}]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y180 [get_cells {swervolf/gpio_rojobot/sync_reg[24]}]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X71Y187 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[0]}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {rojobot31_0_module/inst/BOTREGIF/Sensors_reg[0]}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/gpio_rojobot/sync_reg[3]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[7]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/gpio_rojobot/sync_reg[29]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[3]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5FF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocY_reg[6]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5FF [get_cells {swervolf/gpio_rojobot/sync_reg[27]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5FF [get_cells {swervolf/gpio_rojobot/sync_reg[22]}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5FF [get_cells {swervolf/gpio_rojobot/sync_reg[18]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5FF [get_cells {swervolf/gpio_rojobot/sync_reg[7]}]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5FF [get_cells {swervolf/gpio_rojobot/sync_reg[8]}]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5FF [get_cells {swervolf/gpio_rojobot/sync_reg[5]}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[5]}]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[5]}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {swervolf/gpio_rojobot/sync_reg[26]}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[3]}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocY_reg[2]}]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[2]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X72Y189 [get_cells {rojobot31_0_module/inst/BOTREGIF/Sensors_reg[0]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y195 [get_cells {swervolf/gpio_rojobot/sync_reg[3]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X77Y189 [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[7]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X80Y177 [get_cells {swervolf/gpio_rojobot/sync_reg[29]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X77Y187 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[3]}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X76Y186 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocY_reg[6]}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X78Y179 [get_cells {swervolf/gpio_rojobot/sync_reg[27]}]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X79Y186 [get_cells {swervolf/gpio_rojobot/sync_reg[22]}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X79Y191 [get_cells {swervolf/gpio_rojobot/sync_reg[18]}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X81Y194 [get_cells {swervolf/gpio_rojobot/sync_reg[7]}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X75Y190 [get_cells {swervolf/gpio_rojobot/sync_reg[8]}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X77Y192 [get_cells {swervolf/gpio_rojobot/sync_reg[5]}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X76Y186 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[5]}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X72Y189 [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[5]}]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X78Y179 [get_cells {swervolf/gpio_rojobot/sync_reg[26]}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X77Y189 [get_cells {rojobot31_0_module/inst/BOTREGIF/BotInfo_reg[3]}]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X77Y189 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocY_reg[2]}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X76Y186 [get_cells {rojobot31_0_module/inst/BOTREGIF/LocX_reg[2]}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells ddr2/ldc/storage_8_reg_0_15_0_5_i_19]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[27]}]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[24]}]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[66]}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells ddr2/ldc/storage_10_reg_0_i_77]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q[73]_i_1}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {ddr2/ldc/soc_write_w_buffer_level0_reg[0]}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[30]}]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5LUT [get_cells ddr2/ldc/storage_10_reg_0_i_75]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[32]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[55]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[73]}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells ddr2/ldc/soc_grant_i_2]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells ddr2/ldc/storage_10_reg_0_i_76]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells ddr2/ldc/storage_10_reg_0_i_80]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[39]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5LUT [get_cells ddr2/ldc/storage_6_reg_0_15_0_5_i_8]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL DFF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[40]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A5FF [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[54]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y28 [get_cells ddr2/ldc/storage_8_reg_0_15_0_5_i_19]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X67Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[27]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y55 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[24]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y55 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[66]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y30 [get_cells ddr2/ldc/storage_10_reg_0_i_77]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y45 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q[73]_i_1}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y33 [get_cells {ddr2/ldc/soc_write_w_buffer_level0_reg[0]}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[30]}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X66Y32 [get_cells ddr2/ldc/storage_10_reg_0_i_75]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X67Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[32]}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y55 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[55]}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y55 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[73]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y32 [get_cells ddr2/ldc/soc_grant_i_2]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y34 [get_cells ddr2/ldc/storage_10_reg_0_i_76]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X69Y30 [get_cells ddr2/ldc/storage_10_reg_0_i_80]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X64Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[39]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X68Y31 [get_cells ddr2/ldc/storage_6_reg_0_15_0_5_i_8]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X67Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[40]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X67Y53 [get_cells {cdc/i_axi_cdc/i_cdc_fifo_gray_w/i_dst/i_spill_register/gen_spill_reg.b_data_q_reg[54]}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[26]_i_8__14}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_21]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/dout_reg[13]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_3__5}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D5LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_5__1}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_4__1}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/bp2ff/genblock.dff/dffs/dout_reg[30]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/decode/e3ff/genblock.dff/dffs/dout[0]_i_14}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[2]_i_4__36}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_8__1}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[2]_i_2__19}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_9__0}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_5}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[10]_i_5__18}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/bus_intf/lsu_full_hit_dc3ff/dout[2]_i_2__35}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_16]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells swervolf/swerv_eh1/swerv/dma_ctrl/RdPtr_dff/dffs/i___194_i_61]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_1__10}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[0].stbuf_data_vldff/dffsc/dout[0]_i_70__4}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/bp2ff/genblock.dff/dffs/dout_reg[9]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/pc2ff/genblock.dff/dffs/dout_reg[33]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[16]}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_3__0}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/i__i_3]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsu_pkt_dc1ff/genblock.dff/dffs/dout[10]_i_25}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL CARRY4 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/offsetff/genblock.dff/dffs/dout_reg[3]_i_1__1}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[22]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_25}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_1__3}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/sddc1ff/genblock.dff/dffs/dout[0]_i_1__398}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[5].stbuf_data_vldff/dffsc/dout[10]_i_10__7}]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[19]}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[23]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/pc2ff/genblock.dff/dffs/dout_reg[32]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_29]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL BFF [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/dout_reg[15]}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL AFF [get_cells {swervolf/swerv_eh1/swerv/lsu/dccm_ctl/Gen_dccm_enable.dccm_data_lo_ff/dout_reg[26]}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL C6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsadder/dout[3]_i_3}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_3}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsu_pkt_dc1ff/genblock.dff/dffs/dout[10]_i_18__7}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[0].stbuf_data_vldff/dffsc/dout[10]_i_3__28}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_12]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B6LUT [get_cells swervolf/swerv_eh1/swerv/dec/decode/e2ff/genblock.dff/dffs/i__i_6]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X24Y34 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[26]_i_8__14}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y69 [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_21]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y69 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/dout_reg[13]}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y72 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_3__5}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X24Y47 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_5__1}]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y60 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_4__1}]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X11Y63 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/bp2ff/genblock.dff/dffs/dout_reg[30]}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y69 [get_cells {swervolf/swerv_eh1/swerv/dec/decode/e3ff/genblock.dff/dffs/dout[0]_i_14}]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y40 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[2]_i_4__36}]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X31Y71 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_8__1}]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X25Y48 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[2]_i_2__19}]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y56 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_9__0}]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X22Y49 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_5}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X25Y40 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/stbuf_fwddata_lo_dc3ff/genblock.dff/dffs/dout[10]_i_5__18}]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y40 [get_cells {swervolf/swerv_eh1/swerv/lsu/bus_intf/lsu_full_hit_dc3ff/dout[2]_i_2__35}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X35Y71 [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_16]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X35Y69 [get_cells swervolf/swerv_eh1/swerv/dma_ctrl/RdPtr_dff/dffs/i___194_i_61]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X23Y48 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_1__10}]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y69 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[0].stbuf_data_vldff/dffsc/dout[0]_i_70__4}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y61 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/bp2ff/genblock.dff/dffs/dout_reg[9]}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y62 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/pc2ff/genblock.dff/dffs/dout_reg[33]}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y61 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[16]}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y70 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_3__0}]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y71 [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/i__i_3]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y57 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsu_pkt_dc1ff/genblock.dff/dffs/dout[10]_i_25}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y62 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/offsetff/genblock.dff/dffs/dout_reg[3]_i_1__1}]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y62 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[22]}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y69 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[0]_i_25}]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X19Y49 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_1__3}]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y58 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/sddc1ff/genblock.dff/dffs/dout[0]_i_1__398}]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y56 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[5].stbuf_data_vldff/dffsc/dout[10]_i_10__7}]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X31Y60 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[19]}]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y61 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib2ff/genblock.dff/dffs/dout_reg[23]}]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y61 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/pc2ff/genblock.dff/dffs/dout_reg[32]}]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X34Y69 [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_29]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y68 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/dout_reg[15]}]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X15Y31 [get_cells {swervolf/swerv_eh1/swerv/lsu/dccm_ctl/Gen_dccm_enable.dccm_data_lo_ff/dout_reg[26]}]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X36Y62 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsadder/dout[3]_i_3}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X23Y47 [get_cells {swervolf/swerv_eh1/swerv/dec/instbuff/ib0ff/genblock.dff/dffs/dout[36]_i_3}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X37Y57 [get_cells {swervolf/swerv_eh1/swerv/lsu/lsu_lsc_ctl/lsu_pkt_dc1ff/genblock.dff/dffs/dout[10]_i_18__7}]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y69 [get_cells {swervolf/swerv_eh1/swerv/lsu/stbuf/GenStBuf[0].stbuf_data_vldff/dffsc/dout[10]_i_3__28}]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X31Y72 [get_cells swervolf/swerv_eh1/swerv/dec/instbuff/ib1ff/genblock.dff/dffs/i__i_12]
set_property src_info {type:XDC file:3 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y72 [get_cells swervolf/swerv_eh1/swerv/dec/decode/e2ff/genblock.dff/dffs/i__i_6]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {rojobot31_0_module/inst/LocX_reg[0]}]
