# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sonal/Documents/GitHub/ECE540_Project2/project_2/project_2.srcs/sources_1/ip/Bot_Icon/Bot_Icon.xci
# IP: The module: 'Bot_Icon' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sonal/Documents/GitHub/ECE540_Project2/project_2/project_2.srcs/sources_1/ip/Bot_Icon/Bot_Icon_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bot_Icon'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/sonal/Documents/GitHub/ECE540_Project2/project_2/project_2.srcs/sources_1/ip/Bot_Icon/Bot_Icon.xci
# IP: The module: 'Bot_Icon' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sonal/Documents/GitHub/ECE540_Project2/project_2/project_2.srcs/sources_1/ip/Bot_Icon/Bot_Icon_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bot_Icon'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
